name: Monthly Release

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Date Tag Variable
        run: echo "DATE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Set Release Date
        run: echo "RELEASE_DATE=$(date +'%-B %-Y')" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.10.0+${{ env.DATE_TAG }}
          name: Version v1.10.0+${{ env.DATE_TAG }}
          body: "## ${{ env.RELEASE_DATE }} Update"
          draft: false
          prerelease: false
          make_latest: true
