name: Monthly Release

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download manuf.txt
        run: wget https://raw.githubusercontent.com/kkrypt0nn/manuf/refs/heads/main/manuf.txt -O manuf.txt
      - name: Set Date Tag Variable
        run: echo "DATE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Set Release Date
        run: echo "RELEASE_DATE=$(date +'%-B %-Y')" >> $GITHUB_ENV
      - name: Update README Version
        run: sed -i "s|\(go get github.com/kkrypt0nn/gomanuf@\).*|\1v1.10.0+$DATE_TAG|" README.md
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git add manuf.txt
          git commit -am "chore: Bump version to $VERSION and update manuf.txt"
          git push
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.10.0+${{ env.DATE_TAG }}
          name: Version v1.10.0+${{ env.DATE_TAG }}
          body: "## ${{ env.RELEASE_DATE }} Update"
          draft: false
          prerelease: false
          make_latest: true
